version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: microservices_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  postgres_order:
    image: postgres:latest
    container_name: postgres_order
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_db
    ports:
      - "5433:5432"
    volumes:
      - order_data:/var/lib/postgresql/data

  postgres_stock:
    image: postgres:latest
    container_name: postgres_stock
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stock_db
    ports:
      - "5434:5432"
    volumes:
      - stock_data:/var/lib/postgresql/data

volumes:
  order_data:
  stock_data:
